services:
  django:
    build: ./scar_brackets
    command: gunicorn scar_brackets.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static:/var/www/scar_brackets/static
    expose:
      - 8000
    environment:
      "DEBUG": "True" # TODO remove in prod
    restart: always
  nginx:
    image: nginx:alpine
    depends_on:
      - django
    ports:
      - 8000:80
    volumes:
      - static:/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always

volumes:
  static:
